name: proyecto
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  logger:
  http:
  url_launcher:
  image_picker:
  shared_preferences: 
  firebase_core: 
  firebase_auth: 
  cloud_firestore:
  firebase_storage: 
  cached_network_image:
  smooth_page_indicator: 
  the_apple_sign_in:
  bloc: 
  flutter_bloc:
  flutter_screenutil:
  wave:
  flutter_svg: 
  carousel_slider: 
  flutter_spinkit: 
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  animated_card:
  html:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
